### ISSUE TITLE
视觉编码器问题

### ISSUE THREAD

**Issue by Benny-Yu-stuc** [zjunlp/ContinueMKGC#7]
作者您好，我想请问下，为什么我在调用本地模型进行训练时，导入路径什么的都是正常的，为什么在最后的output中vision_seq_in_text, emissions都是NAN

**Comment by MikeDean2367** [comment]
您好，请问可以提供具体的信息吗？比如执行的脚本、报错的内容，提供更多的信息有助于解决这个问题 :)

**Comment by Benny-Yu-stuc** [comment]
您好，感谢您的及时回复。我在首次运行代码时，模仿您提供的bash文件中的参数设置进行运行的，但是遇到报错RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.      
之后我在代码中将map用的标签从-100修改为-1，同时将ignore参数也修改为-1就可以正常运行了，但这时就出现了，程序不报错，正常运行，但是输出结果一直是NAN，后来我尝试使您之前的代码MKGformer，在路径正确分配的前提下，代码不报错，但是输出loss一直时NAN，输出的矩阵中也全为0

**Comment by Benny-Yu-stuc** [comment]
感谢您的帮助，这个问题我调好了，疑似是电脑环境问题，再次感谢
